export const FALLBACK_UI = {
  menuVisible: true,
  charSelectVisible: false,
  hudVisible: false,
  stageLoadingVisible: false,
  pauseVisible: false,
  comboGuideVisible: false,
  resultVisible: false,
  splashVisible: false,
  fightMode: 'player-vs-cpu',
  soundEnabled: true,
  selectTitle: 'SÉLECTION DU NINJA',
  p1Label: 'NINJA 1',
  p2Label: 'RIVAL',
  selectedPlayerId: null,
  selectedCpuId: null,
  selectedStageId: null,
  stageSelectVisible: false,
  p1Name: '???',
  p2Name: '???',
  roster: [],
  stages: [],
  hud: { p1: null, p2: null, timer: 99, round: 1 },
  loadingTitle: 'Ouverture du jeu',
  loadingMessage: 'Le moteur, le canvas et l’interface se mettent en place.',
  splashText: 'MANCHE 1',
  resultText: 'VICTOIRE !',
  resultWinner: '',
  resultStats: null,
};
